<!DOCTYPE html>
<html>
<head>
	<title>ACCUEIL</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/accueilcss.css">
</head>
<body>
	<header>
		<img style="margin-left:20%;" src="css/adminbanner.png">
	</header>
	<header>
		<nav>
			<ul>
				<li><a href="ACCUEIL.PHP"> Accueil</a></li>
				<li><a href="AJOUTER.PHP">Listes des candidats</a></li>
				<li><a href="">Ajouter un examen</a></li>
				<li><a href="">Ajouter des questions</a></li>
			</ul>
		</nav>
	</header><br><br><br>
	<img src="">

	<div class="adminpanel">

	<h2>Welcome To Control Admin Panel</h2>
	<p>You can manage your user and online exam system from here....</p>
	
    </div>
</body>
</html>